name: Echo Hello Workflow

# Trigger the workflow on push events to the 'main' branch
on:
  push:
    branches:
      - SCRUM-2

jobs:
  hello-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Echo Hello
        run: echo "Hello, World!"
